language: node_js
node_js:
  - "8.0.0"
  - "10.0.0"

os:
  - linux
  - osx

dist: xenial

cache: yarn

addons:
  apt:
    packages:
    - libsecret-1-dev

script:
  - yarn lint
  # TypeScript runs out of memory on Node 8 otherwise.
  # https://stackoverflow.com/a/52390439
  - NODE_OPTIONS=--max_old_space_size=4096 yarn build
  - yarn test:coveralls
