language: node_js
node_js:
  - "8.0.0"
  - "10.0.0"

os:
  - linux
  - osx

dist: trusty

cache: yarn

addons:
  apt:
    packages:
    - libsecret-1-dev

# --runInBand needed so tests don't timeout https://github.com/facebook/jest/issues/3855
script:
  - yarn lint
  - yarn build
  - yarn test --runInBand
