language: node_js
node_js:
  - "10.0.0"
  - "12.0.0"

os:
  - linux
  - osx

dist: xenial

cache: yarn

addons:
  apt:
    packages:
    - libsecret-1-dev

script:
  - yarn lint
  - yarn build
  - yarn test:coveralls
